# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: requirements-txt-fixer
        files: requirements
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        files: .py$
        args:
          - --ignore=E203,E501,E731,W503,W504
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: .py$
        exclude: migrations/
        args:
          - --line-length=100
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        args:
          - -l
          - --recursive
          - -x
          - tests
          - --skip=B101,B608
          # B608 was temporary set because `bandit` doesn't allow multiline string to set `nosec` comment.
        files: .py$
        exclude: migrations/
